# application.yml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/interview_db?serverTimezone=Asia/Seoul
    username: root
    password: 123456

# MyBatis 세팅 (그레들 환경에서 XML 매퍼 파일을 정확히 찾도록 명시)
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true # DB의 snake_case(user_id)를 자바의 camelCase(userId)로 자동 변환

# Ollama 로컬 AI 설정
ollama:
  base-url: http://localhost:11434
  model-name: llama3
