CREATE SEQUENCE INTERVIEW_SESSION_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 면접 질문용 시퀀스 생성
CREATE SEQUENCE QUESTION_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE SEQ_DETAIL_ID
START WITH 1
INCREMENT BY 1
NOCACHE;