spring.application.name=interview

spring.datasource.url=jdbc:mysql://localhost:3306/데이터베이스명?serverTimezone=Asia/Seoul
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=DB사용자아이디
spring.datasource.password=DB비밀번호

# MyBatis Mapper XML 파일 위치 설정 (src/main/resources/mapper/ 내부의 모든 xml 인식)
mybatis.mapper-locations=classpath:mapper/**/*.xml

# Java에서 DB의 snake_case(예: user_id)와 camelCase(예: userId)를 자동으로 매핑해주는 설정
mybatis.configuration.map-underscore-to-camel-case=true